web:
  build: .
  container_name: ap-react
  environment:
    - PORT=8080
  expose:
    - "8080"
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - .:/src
    - /src/node_modules
  command: npm run dev
