web:
  build: .
  container_name: ap-react
  environment:
    - APP_PORT=8088
    - WEBPACK_PORT=8089
    - NODE_ENV=dev
  expose:
    - "8088"
  ports:
    - "8088:8088"
    - "8089:8089"
  volumes:
    - .:/src
    - /src/node_modules
  command: npm run dev
