web:
  build: .
  container_name: ap-react
  environment:
    - APP_PORT=8080
    - WEBPACK_PORT=8081
    - NODE_ENV=dev
  expose:
    - "8080"
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - .:/src
    - /src/node_modules
  command: npm run dev
